/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '2/7/17 12:13 PM' with Gradle 3.1
 *
 * @author Administrator, @date 2/7/17 12:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
